import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/context/cart-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CartProvider>
          {" "}
          {/* Bungkus semua dengan CartProvider */}
          {/* <Navbar /> */}{" "}
          {/* Navbar bisa ditaruh di sini biar bisa akses info keranjang */}
          <main className="main-content-area">
            {" "}
            {/* Kasih class buat styling main content */}
            {children}
          </main>
          {/* Footer bisa di sini juga */}
        </CartProvider>
      </body>
    </html>
  );
}
